### ISSUE TITLE
Bug with Vanilla Coordinates Plugin

### ISSUE THREAD

**Issue by MarcialBD** [Shelly7w7/VanillaCoordinates#1]
Hi Shelly,

Today I made a server in Aternos for Minecraft Bedrock with Plugins (the last version)  and I found yours and I wanted to put it. Everything was normal but then when I tried to activate the command the server crashes and I get kicked out.

Is there any way to solve it? And if there isn't can you patch it?

Here is what the log says when I use the command:

2020-05-06 [11:56:43] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\ConsoleCommandSender::dataPacket()" (EXCEPTION) in "plugins/VanillaCoordinates.phar/src/shelly7w7/VanillaCoordinates/command/CoordinateCommand" at line 37
--
51 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #0 src/pocketmine/command/SimpleCommandMap(248): shelly7w7\VanillaCoordinates\command\CoordinateCommand->execute(object pocketmine\command\ConsoleCommandSender, string[11] coordinates, array[1])
52 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #1 src/pocketmine/Server(1807): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\command\ConsoleCommandSender, string[14] coordinates on)
53 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #2 src/pocketmine/Server(1419): pocketmine\Server->dispatchCommand(object pocketmine\command\ConsoleCommandSender, string[14] coordinates on)
54 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #3 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()
55 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #4 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
56 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #5 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1588759003.7014)
57 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #6 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
58 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #7 src/pocketmine/Server(1584): pocketmine\Server->start()
59 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #8 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /aternos/server/, string[24] /aternos/server/plugins/)
60 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #9 src/pocketmine/PocketMine(296): pocketmine\server()
61 | 2020-05-06 [11:56:43] [Server thread/DEBUG]: #10 (11): require(string[64] phar:///aternos/server/server.phar/src/pocketmine/PocketMine.php)
62 | 2020-05-06 [11:56:43] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
63 | 2020-05-06 [11:56:43] [Server thread/EMERGENCY]: Please upload the "/aternos/server/crashdumps/Wed_May_6-11.56.43-CEST_2020.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
64 | 2020-05-06 [11:56:43] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/4116498 or use the ID #4116498.
65 | 2020-05-06 [11:56:43] [Server thread/INFO]: Disabling VanillaCoordinates v1.0.0
66 | 2020-05-06 [11:56:43] [Server thread/INFO]: MarcialBD left the game
67 | 2020-05-06 [11:56:43] [Server thread/INFO]: MarcialBD[/80.102.126.240:59815] logged out due to Server closed
68 | 2020-05-06 [11:56:43] [Server thread/INFO]: Unloading world "world_"

PS: I don't about programming but I think that this could be useful to fix it

I'm waiting for your answer,
MarcialBD

**Comment by Shelly7w7** [comment]
Fixed in #7aed946
